export const MessageTypes = {
  QUEUE_JOIN: 'queue.join',
  QUEUE_ADDED: 'queue.added',
  QUEUE_LEAVE: 'queue.leave',
  GAME_START: 'game.start',
  GAME_SUBSCRIBE: 'game.subscribe',
  GAME_UPDATE: 'game.update',
  GAME_ERROR: 'game.error',
  DICE_ROLL: 'game.rollDices',
  OPPONENT_UPDATE: 'opponent.update',
  TURN_CHANGE: 'game.turnChange',
  DEFINITIVE_QUIT_GAME: 'game.definitiveQuit',
  PLAYER_QUIT_GAME: 'player.quitGame',
  OPPONENT_RECONNECT: 'opponent.reconnect',
  GAME_RECONNECT: 'game.reconnect',
  PLAYER_FORFEIT: 'player.ff',
  FORFEIT_GAME: 'game.ff',
  OPPONENT_FORFEIT: 'opponent.ff',
  LOCK_DICE: 'game.toggleLock',
  LOCK_DICE_OPPONENT: 'opponent.toggleLock',
};
